#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. Util/CleanFunctions

# Remove surface and features
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/CarBody.eMesh > /dev/null 2>&1
rm -f constant/triSurface/FrontPlug.eMesh > /dev/null 2>&1
rm -f constant/triSurface/FRPlinth.eMesh > /dev/null 2>&1
rm -f constant/triSurface/FRTire.eMesh > /dev/null 2>&1
rm -f constant/triSurface/RadBody.eMesh > /dev/null 2>&1
rm -f constant/triSurface/RadSurface.eMesh > /dev/null 2>&1
rm -f constant/triSurface/RearPlug.eMesh > /dev/null 2>&1
rm -f constant/triSurface/RRPlinth.eMesh > /dev/null 2>&1
rm -f constant/triSurface/RRTire.eMesh > /dev/null 2>&1
rm -f constant/triSurface/Splitter.eMesh > /dev/null 2>&1
rm -f constant/triSurface/Upright.eMesh > /dev/null 2>&1
rm -f constant/triSurface/Wing.eMesh > /dev/null 2>&1
#rm -rf ParaPostPro/
#rm -f ParaPostPro/{*,.*}
#rm -r ParaPostPro/VTK
#rm -r ParaPostPro/postProcessing 
rm -r ParaPostPro/ISO
rm -r ParaPostPro/p
rm -r ParaPostPro/u
rm -r ParaPostPro/tp
rm -r ParaPostPro/mesh
#rm ParaPostPro/log.simpleFoam 

cleanCase

#------------------------------------------------------------------------------

