#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#mkdir ParaPostPro/Images
runApplication surfaceFeatures
runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runParallel patchSummary
#runParallel potentialFoam
#runParallel $(getApplication)
runApplication reconstructParMesh -constant
#runApplication reconstructPar -latestTime
#runApplication postProcess -func "totalPressureIncompressible(p,U)"
#paraFoam --script=ParaPostPro/Macros/Xslices.py
#foamToVTK -latestTime
#mv VTK ParaPostPro
#cp -r postProcessing ParaPostPro
#cp log.simpleFoam ParaPostPro
#cp -r ParaPostPro/ ~/Dropbox/CFD/foamCASES/Current
#checkMesh -allTopology -allGeometry

#------------------------------------------------------------------------------
