#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface and features
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/Car.eMesh > /dev/null 2>&1
#rm -rf ParaPostPro/
#rm -f ParaPostPro/{*,.*}
rm -r ParaPostPro/VTK
rm -r ParaPostPro/postProcessing 
rm -r ParaPostPro/Images
rm ParaPostPro/log.simpleFoam 

cleanCase

#------------------------------------------------------------------------------

