#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd postProcessing/forceCoeffs1/0/
runApplication foamMonitor forceCoeffs.dat

#cd postProcessing/residuals/0/
#runApplication foamMonitor -l residuals.dat

#------------------------------------------------------------------------------
