#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

sleep 5

cd postProcessing/residuals/0/
#rm residuals.dat
#rm residuals_1.dat
rm log.foamMonitor
runApplication foamMonitor -l -t Residuals residuals.dat &
cd ..
cd ..
cd ..

sleep 5

cd postProcessing/carGroupForce/0/
#rm forces.dat
#rm forces_1.dat
rm log.foamMonitor
runApplication foamMonitor -y [-100:100] -t Forces forces.dat &
cd ..
cd ..
cd ..

sleep 5

cd postProcessing/carGroup/0/
#rm forceCoeffs.dat
#rm forceCoeffs_1.dat
rm log.foamMonitor
runApplication foamMonitor -y [-1.0:1.0] -t Coeffs forceCoeffs.dat


#Usage: ${0##*/} [OPTION] <file>
#options:
#  -help     | -h         print the usage
#  -idle     | -i <time>  stops if <file> unchanging for <time> sec (default 60s)
#  -title    | -t <title> set the graph title (default "Data Monitoring")
#  -logscale | -l         plots data (y-axis) on log scale, e.g. for residuals
#  -refresh  | -r <time>  refreshes display every <time> sec (default 10s)
#  -yrange   | -y <range> sets data (y-axis) <range>, format "[0:1]"

# Monitor data with Gnuplot from time-value(s) graphs written by OpenFOAM
# e.g. by functionObjects
# - requires gnuplot, gnuplot_x11

# Example:
#  foamMonitor -l postProcessing/residuals/0/residuals.dat


#------------------------------------------------------------------------------
